version: '2'
services:
    microservicesample-app:
        image: microservicesample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://microservicesample-mysql:3306/microservicesample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    microservicesample-mysql:
        extends:
            file: mysql.yml
            service: microservicesample-mysql
